export const GACHI_STICKERS = {
  unizhen: 'CAACAgIAAxkBAAM7YVl8gWtrPcPzEb10ldrGr9zPBJQAAjIAA17RLBSwpyh9kY826CEE',
  idiNahui: 'CAACAgIAAxkBAAM5YVl8IiZLldLEMOhKNAYpMArqC_QAAgcAA17RLBS-Aj6il9uMliEE',
  govori: 'CAACAgIAAxkBAAM9YVl8m7bGLEQ6Blnnsf1rkw8rlwoAAkYAA17RLBRb06EVc4Z6UyEE',
  oshibsaDveriu: 'CAACAgIAAxkBAAOnYV4C_XlC2DZjXvfZgEvKYaQWR9UAAjgAA17RLBRus1YmxiSIESEE',
  ktoBoss: 'CAACAgIAAxkBAAOpYV4DFT7Qp3utO9CiCwaLkZ_vfyYAAkUAA17RLBQada_0HGBVtSEE',
  goVZal: 'CAACAgIAAxkBAAOkYV4CyLQcm9UZ6I_TOMANo-gte8IAAgsAA17RLBQrHPSKEQ5kbCEE',
}
