export const OTHER_STICKERS = {
  shaUebu: 'CAACAgIAAxkBAAMsYVl09Bfp2PXCSrAygrq4VvbGg1kAAhMQAAJUf1lLC0It1gwGWiAhBA',
  pizdec: 'CAACAgIAAxkBAAOfYV4AAdQVrjC9AVh1G0PDJy-aW-jUAAKECAACXAJlA1T0z6AJhjDrIQQ',
  sukaAgainYou: 'CAACAgIAAxkBAAIOI2FwWPn8VfWdFpiXfCLYA5Rccn4xAAJPBQACIwUNAAEXEoL0wsQXYCEE',
  osuzhdausheSmotryu: 'CAACAgIAAxkBAAIOJGFwW8sV2VOkyejw3yIpZUd0kepQAAKKEQACPLPFB-moAAHP5z0-_iEE',
  importDjango: 'CAACAgIAAxkBAAIOJWFwXxhKHN-ui1IM4mfkYZYMCxfyAAJiAAPi1BkZyzEHcE7N4PohBA',
}
