export const OTHER_STICKERS = {
  shaUebu: 'CAACAgIAAxkBAAMsYVl09Bfp2PXCSrAygrq4VvbGg1kAAhMQAAJUf1lLC0It1gwGWiAhBA',
  pizdec: 'CAACAgIAAxkBAAOfYV4AAdQVrjC9AVh1G0PDJy-aW-jUAAKECAACXAJlA1T0z6AJhjDrIQQ',
}
